### ISSUE TITLE
Blink 4.0.0 cannot start with python3-application

### ISSUE THREAD

**Issue by liviuchircu** [AGProjects/python3-application#1]
It seems python3-application hasn't been fully ported to Python3 yet, as `master` branch Blink (341b8ce5132) complains about some old Python 2 syntax:

![x](https://user-images.githubusercontent.com/4446084/108095853-ff898d80-7088-11eb-8c57-1e206f4d655c.png)

OS: Xubuntu 20.04
`pip3 install python3-application`

Am I doing it wrong, or is `master` branch Blink not functional yet?  Thank you!

**Comment by adigeo** [comment]
You cannot install it using pip3, you must fetch it from our repo

Same for all other dependencies, check their EXACT location here:

https://github.com/AGProjects/python3-sipsimple/blob/master/docs/Install.linux

**Comment by liviuchircu** [comment]
Finally got it to run on Xubuntu 20.04 after a bit of work:

![x](https://user-images.githubusercontent.com/4446084/108118357-ea235c00-70a6-11eb-8926-1bf37a855692.png)

A few comments:

* the suggested `darcs clone http://devel.ag-projects.com/repositories/PROJECT` command does **not** currently work, when replacing "PROJECT" with "python3-application".  The server returns a 403 Forbidden.  I fetched the source code using the tarballs instead.
* there are several unmentioned libraries which also need to be installed before being able to build python3-sipsimple: libv4l-dev, libmpfr-dev, libmpc-dev
* you have to build the PJSIP library and install it to your system! (not mentioned anywhere)
* I also had to install "google-api-python-client" and "oauth2client" through `pip3`

All in all, building Blink 4.0.0 was fun and I enjoyed the challenge - thank you for the help!

**Comment by adigeo** [comment]
Thnaks for the feedback! 

One clue I added to the docs is to check debian/control file for these dependencies.
