### ISSUE TITLE
Examples have python2 shebang

### ISSUE THREAD

**Issue by mcepl** [AGProjects/python3-application#2]
When packaging python3-application (note the name!) I found that all scripts in `examples/` have still `#!/usr/bin/python` shebang which most commonly means using Python 2. It confuses our packaging scripts in openSUSE.

This [patch](https://github.com/AGProjects/python3-application/files/7075845/examples_to_py3k.patch.txt) fixes the problem.

**Comment by adigeo** [comment]
Shebang fixed
